version: '3'
services:
  customer-service:
    build: ./customer-services
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/cafe
    depends_on:
      - mongodb

  order-service:
    build: ./order-services
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/cafe
    depends_on:
      - mongodb

  inventory-service:
    build: ./inventory-services
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/cafe
    depends_on:
      - mongodb

  payment-service:
    build: ./payment-services
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/cafe
    depends_on:
      - mongodb

  menu-service:
    build: ./menu-services
    ports:
      - "3004:3004"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/cafe
    depends_on:
      - mongodb

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - customer-service
      - order-service
      - inventory-service
      - payment-service
      - menu-service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 